# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12buwwH24NQNw_KBwSzPq46zvLBuLxY-S
"""

def Malikov_fan(belgisi):
    if belgisi == "matematika va ingliz tili":
        return "Iqtisodiyot bo'limi"
    elif belgisi == "matematika va fizika":
        return "Dasturiy injiniring bo'limi"
    elif belgisi == "tarix va ingliz tili":
        return "Siyosatshunoslik bo'limi"
    elif belgisi == "ingliz tili va ona tili":
        return "Filologiya bo'limi"
    elif belgisi == "kimyo va biologiya":
        return "Tibbiyot bo'limi"
    elif belgisi == "kimyo va matimatika":
        return "Kimyo texnologiyalar bo'limi"
    elif belgisi == "biologiya va ona tili":
        return "Psixologoya bo'limi"
    elif belgisi == "matematika va ona tili":
        return "Pedogokika bo'limi"
    elif belgisi == "fizka va matematika bo'limi":
        return "Fizka va matematika bo'limi"
    elif belgisi == "":
        return ""
    else:
        return "Bo'lim mavjud emas"

# Take input from the user
belgisi = input("Fanlarni kiriting: ")
natija = Malikov_fan(belgisi)
print(natija)